language: csharp
solution: rna-transcription-csharp-problem.sln
notifications:
  email:
    on_success: always
    on_failure: always
  slack: cgiwave6:lcJAQ85bOZutszEwl7lG0qi4
mono: none
dotnet: 2.1
script:
  - dotnet restore
  - dotnet test MyWebApi.Tests
